# On PR to main run terraform plan to capture required changes in staging environment and check for errors

name: Stage plan

on:
  pull_request:
    branches: [ main ]
    paths: 
    - environments/stage/**
    - terraform/**
  workflow_dispatch:
    
jobs:
  plan:
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Capture Terraform plan of changes
        run: |
          cd environments/stage
          terraform init
          terraform plan -out=../../tfplan  

      - name: Store plan as artefact
        uses: actions/upload-artifact@v2
        with:
          name: stage-plan
          path: tfplan