name: StagePlan

on:
  pull_request:
    branches: [ main ]
    paths: [ environments/stage/** ]
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Capture Terraform plan of changes
        run: |
          cd environments/stage
          terraform plan -out=tfplan  